---
name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "wp-theme_blog-perso.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig README.md"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "wp-theme_blog-perso.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
